name: Build and Release

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: yarn

    - name: Build Project
      run: yarn build
      env:
        NODE_OPTIONS: --openssl-legacy-provider

    - name: Archive Production Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build/
